### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-cdi-porting-tck#1]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538688

**Comment by vinayvishal** [comment]
The job has been created.
https://jenkins.eclipse.org/glassfish/view/glassfish-cdi-porting-tck/job/glassfish-cdi-porting-tck-master-build/
